// Scope browser gesture suppression to touch-sized game layouts.
export function setupMobileViewport() {
    const mobileQuery = matchMedia(
        '(pointer: coarse), (max-width: 900px) and (max-height: 500px)'
    );
    const mobile = () => mobileQuery.matches;
    const viewport = document.querySelector('meta[name="viewport"]');
    const originalViewport = viewport?.getAttribute('content') || '';
    const configureViewport = () =>
        viewport?.setAttribute(
            'content',
            mobile()
                ? `${originalViewport}, maximum-scale=1, user-scalable=no`
                : originalViewport
        );
    configureViewport();
    mobileQuery.addEventListener('change', configureViewport);
    // Cancel Safari's second-tap magnification anywhere, including blank HUD
    // space. Preserve a second intentional button activation when cancelling
    // the compatibility click that would otherwise be generated by touchend.
    let previousTap = 0;
    let startX = 0,
        startY = 0;
    let singleTouch = false;
    document.addEventListener(
        'touchstart',
        (event) => {
            singleTouch = event.touches.length === 1;
            if (singleTouch) {
                startX = event.touches[0].clientX;
                startY = event.touches[0].clientY;
            }
        },
        { passive: true, capture: true }
    );
    document.addEventListener(
        'touchend',
        (event) => {
            if (!mobile() || !singleTouch || event.touches.length) return;
            const touch = event.changedTouches[0];
            if (
                !touch ||
                Math.hypot(touch.clientX - startX, touch.clientY - startY) > 12
            )
                return;
            const now = performance.now();
            if (previousTap > 0 && now - previousTap < 400) {
                const alreadyCancelled = event.defaultPrevented;
                event.preventDefault();
                if (!alreadyCancelled && event.target instanceof Element) {
                    const control = event.target.closest(
                        'button, a, summary, [role="button"]'
                    );
                    if (
                        control instanceof HTMLElement &&
                        !control.matches('[data-key], [data-stick]')
                    )
                        control.click();
                }
            }
            previousTap = now;
        },
        { passive: false }
    );
    for (const type of [
        'selectstart',
        'contextmenu',
        'gesturestart',
        'gesturechange',
        'gestureend',
        'dblclick'
    ]) {
        document.addEventListener(
            type,
            (event) => {
                if (mobile()) event.preventDefault();
            },
            { passive: false }
        );
    }
    // Map pinch uses pointer events; native page magnification must not compete.
    document.addEventListener(
        'touchmove',
        (event) => {
            if (mobile() && event.touches.length > 1) event.preventDefault();
        },
        { passive: false }
    );
    const panel = document.getElementById('flight-data');
    const toggle = document.createElement('button');
    toggle.id = 'mobile-data-toggle';
    toggle.textContent = 'Flight details';
    toggle.setAttribute('aria-expanded', 'false');
    toggle.onclick = () => {
        const open = panel?.classList.toggle('mobile-expanded') ?? false;
        toggle.setAttribute('aria-expanded', String(open));
        toggle.textContent = open ? 'Hide details' : 'Flight details';
    };
    panel?.prepend(toggle);
}
